version: '3.8'
services:
  auth-service:
    image: auth-service:latest
    deploy:
      replicas: 3
    ports:
      - "5000:5000"

  product-service:
    image: product-service:latest
    deploy:
      replicas: 3
    ports:
      - "5001:5000"
